# Generated by Django 4.2.1 on 2023-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
